FROM python:3.10-slim

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home

RUN mkdir -p $DAGSTER_HOME/

COPY dagster.yaml workspace.yaml requirements.txt $DAGSTER_HOME/

RUN pip install -r $DAGSTER_HOME/requirements.txt

WORKDIR $DAGSTER_HOME